### createOrder
POST http://localhost:8080/api/v1/orders HTTP/1.1
content-type: application/json

{
  "date": "2022-03-05",
  "vegetarian": 100,
  "celiac": 100,
  "standard": 100,
  "caloric": 100,
  "ethnic": 100,
  "school": {
    "id": 1
  }
}

### getAllOrders
GET http://localhost:8080/api/v1/orders HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2wiOnsic3ViIjoyLCJlbWFpbCI6InJvYmVydG9AZ21haWwuY29tIiwibmFtZSI6IlJvYmVydG8ifSwiaWF0IjoxNjQ2ODg0NzI0LCJleHAiOjE2NDY5Mjc5MjR9.7J2Tf_qZfoVjcFHdYK1khV_p5c6uK2VZY59OPqvrh0w

### getOneOrder
GET http://localhost:8080/api/v1/orders/2 HTTP/1.1

### rectifyOrder
PUT http://localhost:8080/api/v1/orders/2 HTTP/1.1
content-type: application/json

{
  "isRectified": true,
  "observations": "Se actualizan cantidades",
  "vegetarianReal": 50,
  "celiacReal": 50,
  "standardReal": 75,
  "caloricReal": 50,
  "ethnicReal": 75
}
